### ISSUE TITLE
Endofweek is displayed as week in ISOWeeks hierarchy

### ISSUE THREAD

**Issue by EminUZUN** [marcosqlbi/DaxDateTemplate#1]
![image](https://user-images.githubusercontent.com/8695124/29682977-89355910-8915-11e7-9a5f-76e09eebde20.png)

**Comment by marcosqlbi** [comment]
This makes it easier to use it in charts - would you use another notation (e.g. W01...)?

**Comment by ImkeF** [comment]
Thanks a lot for sharing this comprehensive work! 
Is it possible to make the Last Date dynamic by referencing the date column of a budget table for example?

**Comment by marcosqlbi** [comment]
The columns named "RelativePos..." are there just for this purpose. They are created based on the distance from the processing day obtained using TODAY. You can replace that function with a formula based on another table (e.g. budget). Just modify the assignment of the first variable in the script, "TodayReference".

**Comment by ImkeF** [comment]
Thx, worked a charm!
