### ISSUE TITLE
Redundant Column?

### ISSUE THREAD

**Issue by simonnuss** [marcosqlbi/DaxDateTemplate#4]
Hi Marco

What is the purpose of [Fiscal WeekYearOrder]? (and by extension: [Calendar WeekYearOrder])

The name implies that it is used as the "Sort By Column" for [Fiscal Week Year].  However, [Fiscal YearWeekNumber] serves this purpose in addition to various Time Intelligence methods.

Thanks,
Simon

**Comment by marcosqlbi** [comment]
Simon,

there is a difference between them, see the excerpt from the documentation I'm preparing. Let me know if you have further questions.

Marco

•	Fiscal YearWeekNumber: 6116 (Integer) – Sequential year number across years (a week has always 7 days and a week number can cross one year, between December and January) – it is like Calendar YearWeekNumber
•	Fiscal Week Year: FW30-2018 (String) – Fiscal week and year, sorted by Fiscal WeekYearOrder (a fiscal week can have less than 7 days at start and end of year)
•	Fiscal WeekYearOrder: 201830 (Integer) – Fiscal year and week in format YYYYWW  (a calendar week can have less than 7 days at start and end of year)
