### ISSUE TITLE
Working days no holidays

### ISSUE THREAD

**Issue by luzms** [marcosqlbi/DaxDateTemplate#69]
Hi Marco,
I love your Date DAX table, but I need to calculate working days without holidays. Can you please help me modify the working days line? 
your help is much appreciated.

**Comment by marcosqlbi** [comment]
Just change this line:

```
        VAR IsWorkingDay =
            CONTAINS ( WorkingDays, [WorkingDayNumber], WEEKDAY ( CalDate, 1 ) - 1 )
                && ISBLANK ( [Holiday Name] )

```
to:

```
        VAR IsWorkingDay =
            CONTAINS ( WorkingDays, [WorkingDayNumber], WEEKDAY ( CalDate, 1 ) - 1 )

```

**Comment by luzms** [comment]
Thanks Marco!!! You rock! I love your calendar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
