### ISSUE TITLE
Add Brazilian (BR) holidays

### ISSUE THREAD

**Issue by diegomsg** [marcosqlbi/DaxDateTemplate#70]
Please include the code for Brazilian holidays. Didn't open pull request because i'm not using the latest PBDesktop release.
`            --
            -- BR = Brazil
            { "BR", 1, 1, 0, 0, 0, "Confraternização Universal", 0, 100 },
			{ "BR", 99, -48, 0, 0, 0, "Carnaval", 0, 150 },
			{ "BR", 99, -47, 0, 0, 0, "Carnaval", 0, 150 },
			{ "BR", 99, -2, 0, 0, 0, "Sexta-feira da Paixão", 0, 150 },
			{ "BR", 99, 0, 0, 0, 0, "Páscoa", 0, 150 },
            { "BR", 4, 21, 0, 0, 0, "Tiradentes", 0, 100 },
            { "BR", 5, 1, 0, 0, 0, "Trabalhador", 0, 100 },
			{ "BR", 99, 60, 0, 0, 0, "Corpus Christi", 0, 150 },
            { "BR", 9, 7, 0, 0, 0, "Independência", 0, 100 },
            { "BR", 10, 12, 0, 0, 0, "Nossa Senhora Aparecida", 0, 100 },
            { "BR", 11, 2, 0, 0, 0, "Finados", 0, 100 },
            { "BR", 11, 15, 0, 0, 0, "Proclamação da República", 0, 100 },
            { "BR", 12, 25, 0, 0, 0, "Natal", 0, 100 },`

**Comment by marcosqlbi** [comment]
Hi Diego,

a more updated version of the Date table is available with Bravo for Power BI, which also includes a complete translation in Portuguese.
https://bravo.bi
