### ISSUE TITLE
Fiscal Week

### ISSUE THREAD

**Issue by jasonhendrix** [marcosqlbi/DaxDateTemplate#71]
Using the latest default PBIX file without modifications, creating a table visual that shows 'Fiscal Week Year', 'FW Year', FW StartOfWeek', and 'FW EndOfWeek', it appears that the values are duplicated for Fiscal Week Year values "FW53-2021" and "FW01-2022".  Is that expected behavior?

![image](https://user-images.githubusercontent.com/1486174/189698112-75ee1137-6cd3-464d-ac04-e4a642114366.png)

If I also add the 'Date' field, I can see the following, where 1/1/2022 is the only date in "FW01-2022" but its 'FW StartOfWeek' value is not valid.

![image](https://user-images.githubusercontent.com/1486174/189698588-cfacf680-0ef3-4e39-ad85-f88f15b88a1b.png)

In my case, the report requester is looking for FW53-2021 to look as it does, but for FW01-2022 to start on 2022-01-02 instead of 2022-01-01 as it does above.  Do I need to tweak settings to achieve that, or does the above situation reflect a potential bug?

A sample PBIX showing this issue is attached.  
[DAX Date Template - Fiscal Week Issue.zip](https://github.com/sql-bi/DaxDateTemplate/files/9549684/DAX.Date.Template.-.Fiscal.Week.Issue.zip)

**Comment by marcosqlbi** [comment]
Thanks for reporting the issue.
There is certainly a problem, and the worst news is that also [Bravo for Power BI](https://bravo.bi) has an issue, generating another wrong result for the ISO calendar. I will try to fix the template in Bravo first, then if I have time I'll backport the changes on this template, even though I think we'll deprecate this template because Bravo provides much more flexibility.
However, I'll keep you posted.

**Comment by marcosqlbi** [comment]
@jasonhendrix please, can you try the latest version of [Bravo for Power BI](https://bravo.bi) v0.9.6 released today?

I tried several parameters and they work correctly.
However, I noticed that your requirements do not correspond to US week numbering I am aware of - check these links:
[Year 2021 US](https://www.timeanddate.com/calendar/custom.html?year=2021&country=1&wno=1&holm=1&df=1)
[Year 2022 US](https://www.timeanddate.com/calendar/custom.html?year=2022&country=1&wno=1&holm=1&df=1)

These parameters generate the US calendar described above:
![image](https://user-images.githubusercontent.com/13840816/189950104-2d408e8d-9034-40cb-9680-1d5bcf08efc5.png)

For ISO Calendar, use these parameters:
![image](https://user-images.githubusercontent.com/13840816/189950393-44b8f3b2-9507-4c28-bbd4-121c2873bd1c.png)

In your messsage, you said that you have 53 weeks in 2021, whereas US calendar has 53 weeks in 2022 and ISO calendar has 53 weeks in 2020.

I'd like to know which standard or rule has 53 weeks in 2021.
Thanks!

Marco

**Comment by jasonhendrix** [comment]
Thanks for your help!  Using the latest version of Bravo does seem to give us what we're looking for now.

The 53 weeks piece was probably not an accurate requirement.

**Comment by marcosqlbi** [comment]
Thanks - I'll check whether I can fix the calculation in the DateTemplate, but it's not a high priority now.

**Comment by marcosqlbi** [comment]
I finally realized that in your report you mixed a Fiscal Week column (which is not FW prefixed) with other columns that are FW prefixed. This explains the inconsistency. I can close the issue.
