### ISSUE TITLE
445 QuarterWeekType

### ISSUE THREAD

**Issue by russmatthews** [marcosqlbi/DaxDateTemplate#72]
I have made the settings for line 17 to 445 and line 18 to FiscalWeekly. I'm trying to get a 445 QuarterWeekType but as you can see, it is 444 and creating a 13th period. Is there a setting I am missing to achieve the 445?
![Screenshot 2022-09-12 162543](https://user-images.githubusercontent.com/113391754/189762051-1029334a-add5-4583-8316-7dcb51e6f4c0.png)
![Screenshot 2022-09-12 162717](https://user-images.githubusercontent.com/113391754/189762061-a30a7cde-2ddc-41bf-81d6-d9de2feb3283.png)

**Comment by marcosqlbi** [comment]
FW Period is a fixed 4-week period. You want to use FW Month instead.

**Comment by marcosqlbi** [comment]
Please also consider using [Bravo for Power BI](https://bravo.bi) which is simpler to use and only generates the columns required.
