### ISSUE TITLE
Extend calendar into 2024 and beyond

### ISSUE THREAD

**Issue by jamesgc** [marcosqlbi/DaxDateTemplate#73]
Hello, the calendar seems to stop in 2023. Should I be able to easily extend it into 2024 and beyond? 

Thank you, 
James

**Comment by marcosqlbi** [comment]
It depends on the parameter you set at the beginning of the DAX code. However, take a look at https://bravo.bi which provides a more advanced and flexible way to get a Date table in Power BI.

**Comment by jamesgc** [comment]
OK i will check it out. Thanks.
